Add version to tabulate CMake
p-ranav/tabulate pull request #52
Opened 2020-09-22 11:20 UTC by marimeireles

Fixes #51

2020-09-22 13:08 UTC, p-ranav requested changes

2020-09-22 13:08 UTC, p-ranav commented on include/tabulate/tabulate.hpp
> +#define TABULATE_VERSION_MINOR 1
Wouldn't it be major version 1 and minor version 3?

2020-09-22 13:09 UTC, p-ranav commented
Can you also update the single_include version? Thanks!!

2020-09-22 14:04 UTC, marimeireles commented on include/tabulate/tabulate.hpp
> +#define TABULATE_VERSION_MINOR 1
oh yeah! thanks

2020-09-23 13:53 UTC, p-ranav approved these changes

2020-09-23 13:53 UTC, merged

2020-09-23 13:54 UTC, p-ranav commented
Thank you!