Example of refreshing table contents
p-ranav/tabulate pull request #54
Opened 2020-10-03 10:53 UTC by mohsenomidi

Simple usage real-time refreshing table

2020-10-03 14:57 UTC, p-ranav requested changes

2020-10-03 14:57 UTC, p-ranav commented on samples/refresh_table.cpp
> +  (void)pthread_create(&tId, 0, userInput_thread, 0);
Please change to `std::thread`. `pthread` will not compile in Windows

2020-10-03 14:57 UTC, p-ranav commented on samples/refresh_table.cpp
> +static volatile bool keep_running = true;
Change to `std::atomic_bool`. `keep_running` is modified in a separate `userInput_thread` without locking.

2020-10-04 13:21 UTC, mohsenomidi commented on samples/refresh_table.cpp
> +  (void)pthread_create(&tId, 0, userInput_thread, 0);
Done.

2020-10-04 17:28 UTC, p-ranav commented
Travis build is failing, please check the log here: https://travis-ci.com/github/p-ranav/tabulate/jobs/394791629

You're missing some header includes for thread, chrono, random, vector etc.

2020-10-04 17:42 UTC, mohsenomidi commented on samples/refresh_table.cpp
> +static volatile bool keep_running = true;
Done

2020-10-04 17:44 UTC, mohsenomidi commented
It exists but in my system it compiled without those headers, I think it already included in the original single header file, any way, i will reverted this change and put back the headers.

2020-10-05 05:48 UTC, mohsenomidi commented
All checks done.
@p-ranav Please review.

2020-10-05 11:13 UTC, merged

2020-10-05 11:13 UTC, p-ranav commented
Thanks!